// Code generated by go generate; DO NOT EDIT.

package proto

const (
	EasyTierCommit = "9a2290f312dbdec6f40e8b13d8a6de5f66e4c570"
	SchemaSHA256   = "c145983fee99e08f6207c425cea0952c1aaf50f9bfea12c834d1ec985e0b39df"
)
