// Code generated by go generate; DO NOT EDIT.

package proto

const (
	EasyTierCommit = "63519db2b5f2a6a1b9b7f20905f036dab54eb829"
	SchemaSHA256   = "4fc7f40eac5d3803ed8afe707f2be1db121a022547f91568955c369212875064"
)
