# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#package-ecosystem-

version: 2
updates:
  - package-ecosystem: cargo
    directories:
      - "/"
      - "easytier"
      - "easytier-contrib/easytier-ffi"
      - "easytier-contrib/easytier-ohrs"
      - "easytier-gui/src-tauri"
      - "easytier-rpc-build"
      - "easytier-web"
      - "tauri-plugin-vpnservice"
    schedule:
      interval: weekly
  - package-ecosystem: gradle
    directories:
      - "easytier-gui/src-tauri/gen/android"
      - "easytier-gui/src-tauri/gen/android/app"
      - "easytier-gui/src-tauri/gen/android/buildSrc"
      - "tauri-plugin-vpnservice/android"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directories:
      - "/"
      - "easytier-gui"
      - "easytier-web/frontend"
      - "easytier-web/frontend-lib"
      - "tauri-plugin-vpnservice"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: ".github/workflows"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: swift
    directory: "tauri-plugin-vpnservice/ios"
    schedule:
      interval: weekly
