// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api_manage.proto

package manage

import (
	acl "github.com/EasyTier/EasyTier/easytier-go/proto/acl"
	instance "github.com/EasyTier/EasyTier/easytier-go/proto/api/instance"
	common "github.com/EasyTier/EasyTier/easytier-go/proto/common"
	peer_rpc "github.com/EasyTier/EasyTier/easytier-go/proto/peer_rpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetworkingMethod int32

const (
	NetworkingMethod_PublicServer NetworkingMethod = 0
	NetworkingMethod_Manual       NetworkingMethod = 1
	NetworkingMethod_Standalone   NetworkingMethod = 2
)

// Enum value maps for NetworkingMethod.
var (
	NetworkingMethod_name = map[int32]string{
		0: "PublicServer",
		1: "Manual",
		2: "Standalone",
	}
	NetworkingMethod_value = map[string]int32{
		"PublicServer": 0,
		"Manual":       1,
		"Standalone":   2,
	}
)

func (x NetworkingMethod) Enum() *NetworkingMethod {
	p := new(NetworkingMethod)
	*p = x
	return p
}

func (x NetworkingMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkingMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_api_manage_proto_enumTypes[0].Descriptor()
}

func (NetworkingMethod) Type() protoreflect.EnumType {
	return &file_api_manage_proto_enumTypes[0]
}

func (x NetworkingMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkingMethod.Descriptor instead.
func (NetworkingMethod) EnumDescriptor() ([]byte, []int) {
	return file_api_manage_proto_rawDescGZIP(), []int{0}
}

type ConfigSource int32

const (
	ConfigSource_ConfigSourceUnspecified ConfigSource = 0
	ConfigSource_ConfigSourceUser        ConfigSource = 1
	ConfigSource_ConfigSourceWeb         ConfigSource = 2
)

// Enum value maps for ConfigSource.
var (
	ConfigSource_name = map[int32]string{
		0: "ConfigSourceUnspecified",
		1: "ConfigSourceUser",
		2: "ConfigSourceWeb",
	}
	ConfigSource_value = map[string]int32{
		"ConfigSourceUnspecified": 0,
		"ConfigSourceUser":        1,
		"ConfigSourceWeb":         2,
	}
)

func (x ConfigSource) Enum() *ConfigSource {
	p := new(ConfigSource)
	*p = x
	return p
}

func (x ConfigSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigSource) Descriptor() protoreflect.EnumDescriptor {
	return file_api_manage_proto_enumTypes[1].Descriptor()
}

func (ConfigSource) Type() protoreflect.EnumType {
	return &file_api_manage_proto_enumTypes[1]
}

func (x ConfigSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigSource.Descriptor instead.
func (ConfigSource) EnumDescriptor() ([]byte, []int) {
	return file_api_manage_proto_rawDescGZIP(), []int{1}
}

type NetworkConfig struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	InstanceId                 *string                `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3,oneof" json:"instance_id,omitempty"`
	Dhcp                       *bool                  `protobuf:"varint,2,opt,name=dhcp,proto3,oneof" json:"dhcp,omitempty"`
	VirtualIpv4                *string                `protobuf:"bytes,3,opt,name=virtual_ipv4,json=virtualIpv4,proto3,oneof" json:"virtual_ipv4,omitempty"`
	NetworkLength              *int32                 `protobuf:"varint,4,opt,name=network_length,json=networkLength,proto3,oneof" json:"network_length,omitempty"`
	Hostname                   *string                `protobuf:"bytes,5,opt,name=hostname,proto3,oneof" json:"hostname,omitempty"`
	NetworkName                *string                `protobuf:"bytes,6,opt,name=network_name,json=networkName,proto3,oneof" json:"network_name,omitempty"`
	NetworkSecret              *string                `protobuf:"bytes,7,opt,name=network_secret,json=networkSecret,proto3,oneof" json:"network_secret,omitempty"`
	NetworkingMethod           *NetworkingMethod      `protobuf:"varint,8,opt,name=networking_method,json=networkingMethod,proto3,enum=api.manage.NetworkingMethod,oneof" json:"networking_method,omitempty"`
	PublicServerUrl            *string                `protobuf:"bytes,9,opt,name=public_server_url,json=publicServerUrl,proto3,oneof" json:"public_server_url,omitempty"`
	PeerUrls                   []string               `protobuf:"bytes,10,rep,name=peer_urls,json=peerUrls,proto3" json:"peer_urls,omitempty"`
	ProxyCidrs                 []string               `protobuf:"bytes,11,rep,name=proxy_cidrs,json=proxyCidrs,proto3" json:"proxy_cidrs,omitempty"`
	EnableVpnPortal            *bool                  `protobuf:"varint,12,opt,name=enable_vpn_portal,json=enableVpnPortal,proto3,oneof" json:"enable_vpn_portal,omitempty"`
	VpnPortalListenPort        *int32                 `protobuf:"varint,13,opt,name=vpn_portal_listen_port,json=vpnPortalListenPort,proto3,oneof" json:"vpn_portal_listen_port,omitempty"`
	VpnPortalClientNetworkAddr *string                `protobuf:"bytes,14,opt,name=vpn_portal_client_network_addr,json=vpnPortalClientNetworkAddr,proto3,oneof" json:"vpn_portal_client_network_addr,omitempty"`
	VpnPortalClientNetworkLen  *int32                 `protobuf:"varint,15,opt,name=vpn_portal_client_network_len,json=vpnPortalClientNetworkLen,proto3,oneof" json:"vpn_portal_client_network_len,omitempty"`
	AdvancedSettings           *bool                  `protobuf:"varint,16,opt,name=advanced_settings,json=advancedSettings,proto3,oneof" json:"advanced_settings,omitempty"`
	ListenerUrls               []string               `protobuf:"bytes,17,rep,name=listener_urls,json=listenerUrls,proto3" json:"listener_urls,omitempty"`
	// optional int32 rpc_port = 18;
	LatencyFirst                *bool    `protobuf:"varint,19,opt,name=latency_first,json=latencyFirst,proto3,oneof" json:"latency_first,omitempty"`
	DevName                     *string  `protobuf:"bytes,20,opt,name=dev_name,json=devName,proto3,oneof" json:"dev_name,omitempty"`
	UseSmoltcp                  *bool    `protobuf:"varint,21,opt,name=use_smoltcp,json=useSmoltcp,proto3,oneof" json:"use_smoltcp,omitempty"`
	DisableIpv6                 *bool    `protobuf:"varint,47,opt,name=disable_ipv6,json=disableIpv6,proto3,oneof" json:"disable_ipv6,omitempty"`
	EnableKcpProxy              *bool    `protobuf:"varint,22,opt,name=enable_kcp_proxy,json=enableKcpProxy,proto3,oneof" json:"enable_kcp_proxy,omitempty"`
	DisableKcpInput             *bool    `protobuf:"varint,23,opt,name=disable_kcp_input,json=disableKcpInput,proto3,oneof" json:"disable_kcp_input,omitempty"`
	DisableP2P                  *bool    `protobuf:"varint,24,opt,name=disable_p2p,json=disableP2p,proto3,oneof" json:"disable_p2p,omitempty"`
	BindDevice                  *bool    `protobuf:"varint,25,opt,name=bind_device,json=bindDevice,proto3,oneof" json:"bind_device,omitempty"`
	NoTun                       *bool    `protobuf:"varint,26,opt,name=no_tun,json=noTun,proto3,oneof" json:"no_tun,omitempty"`
	EnableExitNode              *bool    `protobuf:"varint,27,opt,name=enable_exit_node,json=enableExitNode,proto3,oneof" json:"enable_exit_node,omitempty"`
	RelayAllPeerRpc             *bool    `protobuf:"varint,28,opt,name=relay_all_peer_rpc,json=relayAllPeerRpc,proto3,oneof" json:"relay_all_peer_rpc,omitempty"`
	MultiThread                 *bool    `protobuf:"varint,29,opt,name=multi_thread,json=multiThread,proto3,oneof" json:"multi_thread,omitempty"`
	EnableRelayNetworkWhitelist *bool    `protobuf:"varint,30,opt,name=enable_relay_network_whitelist,json=enableRelayNetworkWhitelist,proto3,oneof" json:"enable_relay_network_whitelist,omitempty"`
	RelayNetworkWhitelist       []string `protobuf:"bytes,31,rep,name=relay_network_whitelist,json=relayNetworkWhitelist,proto3" json:"relay_network_whitelist,omitempty"`
	EnableManualRoutes          *bool    `protobuf:"varint,32,opt,name=enable_manual_routes,json=enableManualRoutes,proto3,oneof" json:"enable_manual_routes,omitempty"`
	Routes                      []string `protobuf:"bytes,33,rep,name=routes,proto3" json:"routes,omitempty"`
	ExitNodes                   []string `protobuf:"bytes,34,rep,name=exit_nodes,json=exitNodes,proto3" json:"exit_nodes,omitempty"`
	ProxyForwardBySystem        *bool    `protobuf:"varint,35,opt,name=proxy_forward_by_system,json=proxyForwardBySystem,proto3,oneof" json:"proxy_forward_by_system,omitempty"`
	DisableEncryption           *bool    `protobuf:"varint,36,opt,name=disable_encryption,json=disableEncryption,proto3,oneof" json:"disable_encryption,omitempty"`
	EnableSocks5                *bool    `protobuf:"varint,37,opt,name=enable_socks5,json=enableSocks5,proto3,oneof" json:"enable_socks5,omitempty"`
	Socks5Port                  *int32   `protobuf:"varint,38,opt,name=socks5_port,json=socks5Port,proto3,oneof" json:"socks5_port,omitempty"`
	DisableUdpHolePunching      *bool    `protobuf:"varint,39,opt,name=disable_udp_hole_punching,json=disableUdpHolePunching,proto3,oneof" json:"disable_udp_hole_punching,omitempty"`
	Mtu                         *int32   `protobuf:"varint,40,opt,name=mtu,proto3,oneof" json:"mtu,omitempty"`
	MappedListeners             []string `protobuf:"bytes,41,rep,name=mapped_listeners,json=mappedListeners,proto3" json:"mapped_listeners,omitempty"`
	EnableMagicDns              *bool    `protobuf:"varint,42,opt,name=enable_magic_dns,json=enableMagicDns,proto3,oneof" json:"enable_magic_dns,omitempty"`
	EnablePrivateMode           *bool    `protobuf:"varint,43,opt,name=enable_private_mode,json=enablePrivateMode,proto3,oneof" json:"enable_private_mode,omitempty"`
	EnableQuicProxy             *bool    `protobuf:"varint,45,opt,name=enable_quic_proxy,json=enableQuicProxy,proto3,oneof" json:"enable_quic_proxy,omitempty"`
	DisableQuicInput            *bool    `protobuf:"varint,46,opt,name=disable_quic_input,json=disableQuicInput,proto3,oneof" json:"disable_quic_input,omitempty"`
	// Deprecated: Marked as deprecated in api_manage.proto.
	QuicListenPort          *int32                    `protobuf:"varint,50,opt,name=quic_listen_port,json=quicListenPort,proto3,oneof" json:"quic_listen_port,omitempty"`
	PortForwards            []*PortForwardConfig      `protobuf:"bytes,48,rep,name=port_forwards,json=portForwards,proto3" json:"port_forwards,omitempty"`
	DisableSymHolePunching  *bool                     `protobuf:"varint,49,opt,name=disable_sym_hole_punching,json=disableSymHolePunching,proto3,oneof" json:"disable_sym_hole_punching,omitempty"`
	P2POnly                 *bool                     `protobuf:"varint,51,opt,name=p2p_only,json=p2pOnly,proto3,oneof" json:"p2p_only,omitempty"`
	DataCompressAlgo        *common.CompressionAlgoPb `protobuf:"varint,52,opt,name=data_compress_algo,json=dataCompressAlgo,proto3,enum=common.CompressionAlgoPb,oneof" json:"data_compress_algo,omitempty"`
	EncryptionAlgorithm     *string                   `protobuf:"bytes,53,opt,name=encryption_algorithm,json=encryptionAlgorithm,proto3,oneof" json:"encryption_algorithm,omitempty"`
	DisableTcpHolePunching  *bool                     `protobuf:"varint,54,opt,name=disable_tcp_hole_punching,json=disableTcpHolePunching,proto3,oneof" json:"disable_tcp_hole_punching,omitempty"`
	SecureMode              *common.SecureModeConfig  `protobuf:"bytes,55,opt,name=secure_mode,json=secureMode,proto3" json:"secure_mode,omitempty"`
	Acl                     *acl.Acl                  `protobuf:"bytes,56,opt,name=acl,proto3,oneof" json:"acl,omitempty"`
	CredentialFile          *string                   `protobuf:"bytes,57,opt,name=credential_file,json=credentialFile,proto3,oneof" json:"credential_file,omitempty"`
	LazyP2P                 *bool                     `protobuf:"varint,58,opt,name=lazy_p2p,json=lazyP2p,proto3,oneof" json:"lazy_p2p,omitempty"`
	NeedP2P                 *bool                     `protobuf:"varint,59,opt,name=need_p2p,json=needP2p,proto3,oneof" json:"need_p2p,omitempty"`
	InstanceRecvBpsLimit    *uint64                   `protobuf:"varint,60,opt,name=instance_recv_bps_limit,json=instanceRecvBpsLimit,proto3,oneof" json:"instance_recv_bps_limit,omitempty"`
	DisableUpnp             *bool                     `protobuf:"varint,61,opt,name=disable_upnp,json=disableUpnp,proto3,oneof" json:"disable_upnp,omitempty"`
	Ipv6PublicAddrProvider  *bool                     `protobuf:"varint,62,opt,name=ipv6_public_addr_provider,json=ipv6PublicAddrProvider,proto3,oneof" json:"ipv6_public_addr_provider,omitempty"`
	Ipv6PublicAddrAuto      *bool                     `protobuf:"varint,63,opt,name=ipv6_public_addr_auto,json=ipv6PublicAddrAuto,proto3,oneof" json:"ipv6_public_addr_auto,omitempty"`
	Ipv6PublicAddrPrefix    *string                   `protobuf:"bytes,64,opt,name=ipv6_public_addr_prefix,json=ipv6PublicAddrPrefix,proto3,oneof" json:"ipv6_public_addr_prefix,omitempty"`
	DisableRelayData        *bool                     `protobuf:"varint,65,opt,name=disable_relay_data,json=disableRelayData,proto3,oneof" json:"disable_relay_data,omitempty"`
	EnableUdpBroadcastRelay *bool                     `protobuf:"varint,66,opt,name=enable_udp_broadcast_relay,json=enableUdpBroadcastRelay,proto3,oneof" json:"enable_udp_broadcast_relay,omitempty"`
	SocketMark              *uint32                   `protobuf:"varint,67,opt,name=socket_mark,json=socketMark,proto3,oneof" json:"socket_mark,omitempty"`
	Peers                   []*NetworkPeerConfig      `protobuf:"bytes,68,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *NetworkConfig) Reset() {
	*x = NetworkConfig{}
	mi := &file_api_manage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConfig) ProtoMessage() {}

func (x *NetworkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConfig.ProtoReflect.Descriptor instead.
func (*NetworkConfig) Descriptor() ([]byte, []int) {
	return file_api_manage_proto_rawDescGZIP(), []int{0}
}

func (x *NetworkConfig) GetInstanceId() string {
	if x != nil && x.InstanceId != nil {
		return *x.InstanceId
	}
	return ""
}

func (x *NetworkConfig) GetDhcp() bool {
	if x != nil && x.Dhcp != nil {
		return *x.Dhcp
	}
	return false
}

func (x *NetworkConfig) GetVirtualIpv4() string {
	if x != nil && x.VirtualIpv4 != nil {
		return *x.VirtualIpv4
	}
	return ""
}

func (x *NetworkConfig) GetNetworkLength() int32 {
	if x != nil && x.NetworkLength != nil {
		return *x.NetworkLength
	}
	return 0
}

func (x *NetworkConfig) GetHostname() string {
	if x != nil && x.Hostname != nil {
		return *x.Hostname
	}
	return ""
}

func (x *NetworkConfig) GetNetworkName() string {
	if x != nil && x.NetworkName != nil {
		return *x.NetworkName
	}
	return ""
}

func (x *NetworkConfig) GetNetworkSecret() string {
	if x != nil && x.NetworkSecret != nil {
		return *x.NetworkSecret
	}
	return ""
}

func (x *NetworkConfig) GetNetworkingMethod() NetworkingMethod {
	if x != nil && x.NetworkingMethod != nil {
		return *x.NetworkingMethod
	}
	return NetworkingMethod_PublicServer
}

func (x *NetworkConfig) GetPublicServerUrl() string {
	if x != nil && x.PublicServerUrl != nil {
		return *x.PublicServerUrl
	}
	return ""
}

func (x *NetworkConfig) GetPeerUrls() []string {
	if x != nil {
		return x.PeerUrls
	}
	return nil
}

func (x *NetworkConfig) GetProxyCidrs() []string {
	if x != nil {
		return x.ProxyCidrs
	}
	return nil
}

func (x *NetworkConfig) GetEnableVpnPortal() bool {
	if x != nil && x.EnableVpnPortal != nil {
		return *x.EnableVpnPortal
	}
	return false
}

func (x *NetworkConfig) GetVpnPortalListenPort() int32 {
	if x != nil && x.VpnPortalListenPort != nil {
		return *x.VpnPortalListenPort
	}
	return 0
}

func (x *NetworkConfig) GetVpnPortalClientNetworkAddr() string {
	if x != nil && x.VpnPortalClientNetworkAddr != nil {
		return *x.VpnPortalClientNetworkAddr
	}
	return ""
}

func (x *NetworkConfig) GetVpnPortalClientNetworkLen() int32 {
	if x != nil && x.VpnPortalClientNetworkLen != nil {
		return *x.VpnPortalClientNetworkLen
	}
	return 0
}

func (x *NetworkConfig) GetAdvancedSettings() bool {
	if x != nil && x.AdvancedSettings != nil {
		return *x.AdvancedSettings
	}
	return false
}

func (x *NetworkConfig) GetListenerUrls() []string {
	if x != nil {
		return x.ListenerUrls
	}
	return nil
}

func (x *NetworkConfig) GetLatencyFirst() bool {
	if x != nil && x.LatencyFirst != nil {
		return *x.LatencyFirst
	}
	return false
}

func (x *NetworkConfig) GetDevName() string {
	if x != nil && x.DevName != nil {
		return *x.DevName
	}
	return ""
}

func (x *NetworkConfig) GetUseSmoltcp() bool {
	if x != nil && x.UseSmoltcp != nil {
		return *x.UseSmoltcp
	}
	return false
}

func (x *NetworkConfig) GetDisableIpv6() bool {
	if x != nil && x.DisableIpv6 != nil {
		return *x.DisableIpv6
	}
	return false
}

func (x *NetworkConfig) GetEnableKcpProxy() bool {
	if x != nil && x.EnableKcpProxy != nil {
		return *x.EnableKcpProxy
	}
	return false
}

func (x *NetworkConfig) GetDisableKcpInput() bool {
	if x != nil && x.DisableKcpInput != nil {
		return *x.DisableKcpInput
	}
	return false
}

func (x *NetworkConfig) GetDisableP2P() bool {
	if x != nil && x.DisableP2P != nil {
		return *x.DisableP2P
	}
	return false
}

func (x *NetworkConfig) GetBindDevice() bool {
	if x != nil && x.BindDevice != nil {
		return *x.BindDevice
	}
	return false
}

func (x *NetworkConfig) GetNoTun() bool {
	if x != nil && x.NoTun != nil {
		return *x.NoTun
	}
	return false
}

func (x *NetworkConfig) GetEnableExitNode() bool {
	if x != nil && x.EnableExitNode != nil {
		return *x.EnableExitNode
	}
	return false
}

func (x *NetworkConfig) GetRelayAllPeerRpc() bool {
	if x != nil && x.RelayAllPeerRpc != nil {
		return *x.RelayAllPeerRpc
	}
	return false
}

func (x *NetworkConfig) GetMultiThread() bool {
	if x != nil && x.MultiThread != nil {
		return *x.MultiThread
	}
	return false
}

func (x *NetworkConfig) GetEnableRelayNetworkWhitelist() bool {
	if x != nil && x.EnableRelayNetworkWhitelist != nil {
		return *x.EnableRelayNetworkWhitelist
	}
	return false
}

func (x *NetworkConfig) GetRelayNetworkWhitelist() []string {
	if x != nil {
		return x.RelayNetworkWhitelist
	}
	return nil
}

func (x *NetworkConfig) GetEnableManualRoutes() bool {
	if x != nil && x.EnableManualRoutes != nil {
		return *x.EnableManualRoutes
	}
	return false
}

func (x *NetworkConfig) GetRoutes() []string {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *NetworkConfig) GetExitNodes() []string {
	if x != nil {
		return x.ExitNodes
	}
	return nil
}

func (x *NetworkConfig) GetProxyForwardBySystem() bool {
	if x != nil && x.ProxyForwardBySystem != nil {
		return *x.ProxyForwardBySystem
	}
	return false
}

func (x *NetworkConfig) GetDisableEncryption() bool {
	if x != nil && x.DisableEncryption != nil {
		return *x.DisableEncryption
	}
	return false
}

func (x *NetworkConfig) GetEnableSocks5() bool {
	if x != nil && x.EnableSocks5 != nil {
		return *x.EnableSocks5
	}
	return false
}

func (x *NetworkConfig) GetSocks5Port() int32 {
	if x != nil && x.Socks5Port != nil {
		return *x.Socks5Port
	}
	return 0
}

func (x *NetworkConfig) GetDisableUdpHolePunching() bool {
	if x != nil && x.DisableUdpHolePunching != nil {
		return *x.DisableUdpHolePunching
	}
	return false
}

func (x *NetworkConfig) GetMtu() int32 {
	if x != nil && x.Mtu != nil {
		return *x.Mtu
	}
	return 0
}

func (x *NetworkConfig) GetMappedListeners() []string {
	if x != nil {
		return x.MappedListeners
	}
	return nil
}

func (x *NetworkConfig) GetEnableMagicDns() bool {
	if x != nil && x.EnableMagicDns != nil {
		return *x.EnableMagicDns
	}
	return false
}

func (x *NetworkConfig) GetEnablePrivateMode() bool {
	if x != nil && x.EnablePrivateMode != nil {
		return *x.EnablePrivateMode
	}
	return false
}

func (x *NetworkConfig) GetEnableQuicProxy() bool {
	if x != nil && x.EnableQuicProxy != nil {
		return *x.EnableQuicProxy
	}
	return false
}

func (x *NetworkConfig) GetDisableQuicInput() bool {
	if x != nil && x.DisableQuicInput != nil {
		return *x.DisableQuicInput
	}
	return false
}

// Deprecated: Marked as deprecated in api_manage.proto.
func (x *NetworkConfig) GetQuicListenPort() int32 {
	if x != nil && x.QuicListenPort != nil {
		return *x.QuicListenPort
	}
	return 0
}

func (x *NetworkConfig) GetPortForwards() []*PortForwardConfig {
	if x != nil {
		return x.PortForwards
	}
	return nil
}

func (x *NetworkConfig) GetDisableSymHolePunching() bool {
	if x != nil && x.DisableSymHolePunching != nil {
		return *x.DisableSymHolePunching
	}
	return false
}

func (x *NetworkConfig) GetP2POnly() bool {
	if x != nil && x.P2POnly != nil {
		return *x.P2POnly
	}
	return false
}

func (x *NetworkConfig) GetDataCompressAlgo() common.CompressionAlgoPb {
	if x != nil && x.DataCompressAlgo != nil {
		return *x.DataCompressAlgo
	}
	return common.CompressionAlgoPb(0)
}

func (x *NetworkConfig) GetEncryptionAlgorithm() string {
	if x != nil && x.EncryptionAlgorithm != nil {
		return *x.EncryptionAlgorithm
	}
	return ""
}

func (x *NetworkConfig) GetDisableTcpHolePunching() bool {
	if x != nil && x.DisableTcpHolePunching != nil {
		return *x.DisableTcpHolePunching
	}
	return false
}

func (x *NetworkConfig) GetSecureMode() *common.SecureModeConfig {
	if x != nil {
		return x.SecureMode
	}
	return nil
}

func (x *NetworkConfig) GetAcl() *acl.Acl {
	if x != nil {
		return x.Acl
	}
	return nil
}

func (x *NetworkConfig) GetCredentialFile() string {
	if x != nil && x.CredentialFile != nil {
		return *x.CredentialFile
	}
	return ""
}

func (x *NetworkConfig) GetLazyP2P() bool {
	if x != nil && x.LazyP2P != nil {
		return *x.LazyP2P
	}
	return false
}

func (x *NetworkConfig) GetNeedP2P() bool {
	if x != nil && x.NeedP2P != nil {
		return *x.NeedP2P
	}
	return false
}

func (x *NetworkConfig) GetInstanceRecvBpsLimit() uint64 {
	if x != nil && x.InstanceRecvBpsLimit != nil {
		return *x.InstanceRecvBpsLimit
	}
	return 0
}

func (x *NetworkConfig) GetDisableUpnp() bool {
	if x != nil && x.DisableUpnp != nil {
		return *x.DisableUpnp
	}
	return false
}

func (x *NetworkConfig) GetIpv6PublicAddrProvider() bool {
	if x != nil && x.Ipv6PublicAddrProvider != nil {
		return *x.Ipv6PublicAddrProvider
	}
	return false
}

func (x *NetworkConfig) GetIpv6PublicAddrAuto() bool {
	if x != nil && x.Ipv6PublicAddrAuto != nil {
		return *x.Ipv6PublicAddrAuto
	}
	return false
}

func (x *NetworkConfig) GetIpv6PublicAddrPrefix() string {
	if x != nil && x.Ipv6PublicAddrPrefix != nil {
		return *x.Ipv6PublicAddrPrefix
	}
	return ""
}

func (x *NetworkConfig) GetDisableRelayData() bool {
	if x != nil && x.DisableRelayData != nil {
		return *x.DisableRelayData
	}
	return false
}

func (x *NetworkConfig) GetEnableUdpBroadcastRelay() bool {
	if x != nil && x.EnableUdpBroadcastRelay != nil {
		return *x.EnableUdpBroadcastRelay
	}
	return false
}

func (x *NetworkConfig) GetSocketMark() uint32 {
	if x != nil && x.SocketMark != nil {
		return *x.SocketMark
	}
	return 0
}

func (x *NetworkConfig) GetPeers() []*NetworkPeerConfig {
	if x != nil {
		return x.Peers
	}
	return nil
}

type NetworkPeerConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	PeerPublicKey *string                `protobuf:"bytes,2,opt,name=peer_public_key,json=peerPublicKey,proto3,oneof" json:"peer_public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPeerConfig) Reset() {
	*x = NetworkPeerConfig{}
	mi := &file_api_manage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPeerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPeerConfig) ProtoMessage() {}

func (x *NetworkPeerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPeerConfig.ProtoReflect.Descriptor instead.
func (*NetworkPeerConfig) Descriptor() ([]byte, []int) {
	return file_api_manage_proto_rawDescGZIP(), []int{1}
}

func (x *NetworkPeerConfig) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *NetworkPeerConfig) GetPeerPublicKey() string {
	if x != nil && x.PeerPublicKey != nil {
		return *x.PeerPublicKey
	}
	return ""
}

type PortForwardConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BindIp        string                 `protobuf:"bytes,1,opt,name=bind_ip,json=bindIp,proto3" json:"bind_ip,omitempty"`
	BindPort      uint32                 `protobuf:"varint,2,opt,name=bind_port,json=bindPort,proto3" json:"bind_port,omitempty"`
	DstIp         string                 `protobuf:"bytes,3,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	DstPort       uint32                 `protobuf:"varint,4,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	Proto         string                 `protobuf:"bytes,5,opt,name=proto,proto3" json:"proto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortForwardConfig) Reset() {
	*x = PortForwardConfig{}
	mi := &file_api_manage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardConfig) ProtoMessage() {}

func (x *PortForwardConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortForwardConfig.ProtoReflect.Descriptor instead.
func (*PortForwardConfig) Descriptor() ([]byte, []int) {
	return file_api_manage_proto_rawDescGZIP(), []int{2}
}

func (x *PortForwardConfig) GetBindIp() string {
	if x != nil {
		return x.BindIp
	}
	return ""
}

func (x *PortForwardConfig) GetBindPort() uint32 {
	if x != nil {
		return x.BindPort
	}
	return 0
}

func (x *PortForwardConfig) GetDstIp() string {
	if x != nil {
		return x.DstIp
	}
	return ""
}

func (x *PortForwardConfig) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *PortForwardConfig) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

type MyNodeInfo struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	VirtualIpv4   *common.Ipv4Inet            `protobuf:"bytes,1,opt,name=virtual_ipv4,json=virtualIpv4,proto3" json:"virtual_ipv4,omitempty"`
	Hostname      string                      `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Version       string                      `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Ips           *peer_rpc.GetIpListResponse `protobuf:"bytes,4,opt,name=ips,proto3" json:"ips,omitempty"`
	StunInfo      *common.StunInfo            `protobuf:"bytes,5,opt,name=stun_info,json=stunInfo,proto3" json:"stun_info,omitempty"`
	Listeners     []*common.Url               `protobuf:"bytes,6,rep,name=listeners,proto3" json:"listeners,omitempty"`
	VpnPortalCfg  *string                     `protobuf:"bytes,7,opt,name=vpn_portal_cfg,json=vpnPortalCfg,proto3,oneof" json:"vpn_portal_cfg,omitempty"`
	PeerId        uint32                      `protobuf:"varint,8,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyNodeInfo) Reset() {
	*x = MyNodeInfo{}
	mi := &file_api_manage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyNodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyNodeInfo) ProtoMessage() {}

func (x *MyNodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyNodeInfo.ProtoReflect.Descriptor instead.
func (*MyNodeInfo) Descriptor() ([]byte, []int) {
	return file_api_manage_proto_rawDescGZIP(), []int{3}
}

func (x *MyNodeInfo) GetVirtualIpv4() *common.Ipv4Inet {
	if x != nil {
		return x.VirtualIpv4
	}
	return nil
}

func (x *MyNodeInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *MyNodeInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MyNodeInfo) GetIps() *peer_rpc.GetIpListResponse {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *MyNodeInfo) GetStunInfo() *common.StunInfo {
	if x != nil {
		return x.StunInfo
	}
	return nil
}

func (x *MyNodeInfo) GetListeners() []*common.Url {
	if x != nil {
		return x.Listeners
	}
	return nil
}

func (x *MyNodeInfo) GetVpnPortalCfg() string {
	if x != nil && x.VpnPortalCfg != nil {
		return *x.VpnPortalCfg
	}
	return ""
}

func (x *MyNodeInfo) GetPeerId() uint32 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

type NetworkInstanceRunningInfo struct {
	state                 protoimpl.MessageState               `protogen:"open.v1"`
	DevName               string                               `protobuf:"bytes,1,opt,name=dev_name,json=devName,proto3" json:"dev_name,omitempty"`
	MyNodeInfo            *MyNodeInfo                          `protobuf:"bytes,2,opt,name=my_node_info,json=myNodeInfo,proto3" json:"my_node_info,omitempty"`
	Events                []string                             `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	Routes                []*instance.Route                    `protobuf:"bytes,4,rep,name=routes,proto3" json:"routes,omitempty"`
	Peers                 []*instance.PeerInfo                 `protobuf:"bytes,5,rep,name=peers,proto3" json:"peers,omitempty"`
	PeerRoutePairs        []*instance.PeerRoutePair            `protobuf:"bytes,6,rep,name=peer_route_pairs,json=peerRoutePairs,proto3" json:"peer_route_pairs,omitempty"`
	Running               bool                                 `protobuf:"varint,7,opt,name=running,proto3" json:"running,omitempty"`
	ErrorMsg              *string                              `protobuf:"bytes,8,opt,name=error_msg,json=errorMsg,proto3,oneof" json:"error_msg,omitempty"`
	ForeignNetworkSummary *peer_rpc.RouteForeignNetworkSummary `protobuf:"bytes,9,opt,name=foreign_network_summary,json=foreignNetworkSummary,proto3" json:"foreign_network_summary,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *NetworkInstanceRunningInfo) Reset() {
	*x = NetworkInstanceRunningInfo{}
	mi := &file_api_manage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInstanceRunningInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInstanceRunningInfo) ProtoMessage() {}

func (x *NetworkInstanceRunningInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInstanceRunningInfo.ProtoReflect.Descriptor instead.
func (*NetworkInstanceRunningInfo) Descriptor() ([]byte, []int) {
	return file_api_manage_proto_rawDescGZIP(), []int{4}
}

func (x *NetworkInstanceRunningInfo) GetDevName() string {
	if x != nil {
		return x.DevName
	}
	return ""
}

func (x *NetworkInstanceRunningInfo) GetMyNodeInfo() *MyNodeInfo {
	if x != nil {
		return x.MyNodeInfo
	}
	return nil
}

func (x *NetworkInstanceRunningInfo) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *NetworkInstanceRunningInfo) GetRoutes() []*instance.Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *NetworkInstanceRunningInfo) GetPeers() []*instance.PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *NetworkInstanceRunningInfo) GetPeerRoutePairs() []*instance.PeerRoutePair {
	if x != nil {
		return x.PeerRoutePairs
	}
	return nil
}

func (x *NetworkInstanceRunningInfo) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *NetworkInstanceRunningInfo) GetErrorMsg() string {
	if x != nil && x.ErrorMsg != nil {
		return *x.ErrorMsg
	}
	return ""
}

func (x *NetworkInstanceRunningInfo) GetForeignNetworkSummary() *peer_rpc.RouteForeignNetworkSummary {
	if x != nil {
		return x.ForeignNetworkSummary
	}
	return nil
}

type NetworkInstanceRunningInfoMap struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Map           map[string]*NetworkInstanceRunningInfo `protobuf:"bytes,1,rep,name=map,proto3" json:"map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInstanceRunningInfoMap) Reset() {
	*x = NetworkInstanceRunningInfoMap{}
	mi := &file_api_manage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInstanceRunningInfoMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInstanceRunningInfoMap) ProtoMessage() {}

func (x *NetworkInstanceRunningInfoMap) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInstanceRunningInfoMap.ProtoReflect.Descriptor instead.
func (*NetworkInstanceRunningInfoMap) Descriptor() ([]byte, []int) {
	return file_api_manage_proto_rawDescGZIP(), []int{5}
}

func (x *NetworkInstanceRunningInfoMap) GetMap() map[string]*NetworkInstanceRunningInfo {
	if x != nil {
		return x.Map
	}
	return nil
}

type NetworkMeta struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	InstId           *common.UUID           `protobuf:"bytes,1,opt,name=inst_id,json=instId,proto3" json:"inst_id,omitempty"`
	NetworkName      string                 `protobuf:"bytes,2,opt,name=network_name,json=networkName,proto3" json:"network_name,omitempty"`
	ConfigPermission uint32                 `protobuf:"varint,3,opt,name=config_permission,json=configPermission,proto3" json:"config_permission,omitempty"`
	InstanceName     string                 `protobuf:"bytes,4,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	Source           ConfigSource           `protobuf:"varint,5,opt,name=source,proto3,enum=api.manage.ConfigSource" json:"source,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NetworkMeta) Reset() {
	*x = NetworkMeta{}
	mi := &file_api_manage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMeta) ProtoMessage() {}

func (x *NetworkMeta) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMeta.ProtoReflect.Descriptor instead.
func (*NetworkMeta) Descriptor() ([]byte, []int) {
	return file_api_manage_proto_rawDescGZIP(), []int{6}
}

func (x *NetworkMeta) GetInstId() *common.UUID {
	if x != nil {
		return x.InstId
	}
	return nil
}

func (x *NetworkMeta) GetNetworkName() string {
	if x != nil {
		return x.NetworkName
	}
	return ""
}

func (x *NetworkMeta) GetConfigPermission() uint32 {
	if x != nil {
		return x.ConfigPermission
	}
	return 0
}

func (x *NetworkMeta) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *NetworkMeta) GetSource() ConfigSource {
	if x != nil {
		return x.Source
	}
	return ConfigSource_ConfigSourceUnspecified
}

type ValidateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *NetworkConfig         `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateConfigRequest) Reset() {
	*x = ValidateConfigRequest{}
	mi := &file_api_manage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigRequest) ProtoMessage() {}

func (x *ValidateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConfigRequest.ProtoReflect.Descriptor instead.
func (*ValidateConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_manage_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateConfigRequest) GetConfig() *NetworkConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type ValidateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TomlConfig    string                 `protobuf:"bytes,1,opt,name=toml_config,json=tomlConfig,proto3" json:"toml_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateConfigResponse) Reset() {
	*x = ValidateConfigResponse{}
	mi := &file_api_manage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigResponse) ProtoMessage() {}

func (x *ValidateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConfigResponse.ProtoReflect.Descriptor instead.
func (*ValidateConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_manage_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateConfigResponse) GetTomlConfig() string {
	if x != nil {
		return x.TomlConfig
	}
	return ""
}

type RunNetworkInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstId        *common.UUID           `protobuf:"bytes,1,opt,name=inst_id,json=instId,proto3" json:"inst_id,omitempty"`
	Config        *NetworkConfig         `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	Overwrite     bool                   `protobuf:"varint,3,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
	Source        ConfigSource           `protobuf:"varint,4,opt,name=source,proto3,enum=api.manage.ConfigSource" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunNetworkInstanceRequest) Reset() {
	*x = RunNetworkInstanceRequest{}
	mi := &file_api_manage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunNetworkInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunNetworkInstanceRequest) ProtoMessage() {}

func (x *RunNetworkInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunNetworkInstanceRequest.ProtoReflect.Descriptor instead.
func (*RunNetworkInstanceRequest) Descriptor() ([]byte, []int) {
	return file_api_manage_proto_rawDescGZIP(), []int{9}
}

func (x *RunNetworkInstanceRequest) GetInstId() *common.UUID {
	if x != nil {
		return x.InstId
	}
	return nil
}

func (x *RunNetworkInstanceRequest) GetConfig() *NetworkConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *RunNetworkInstanceRequest) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

func (x *RunNetworkInstanceRequest) GetSource() ConfigSource {
	if x != nil {
		return x.Source
	}
	return ConfigSource_ConfigSourceUnspecified
}

type RunNetworkInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstId        *common.UUID           `protobuf:"bytes,1,opt,name=inst_id,json=instId,proto3" json:"inst_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunNetworkInstanceResponse) Reset() {
	*x = RunNetworkInstanceResponse{}
	mi := &file_api_manage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunNetworkInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunNetworkInstanceResponse) ProtoMessage() {}

func (x *RunNetworkInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunNetworkInstanceResponse.ProtoReflect.Descriptor instead.
func (*RunNetworkInstanceResponse) Descriptor() ([]byte, []int) {
	return file_api_manage_proto_rawDescGZIP(), []int{10}
}

func (x *RunNetworkInstanceResponse) GetInstId() *common.UUID {
	if x != nil {
		return x.InstId
	}
	return nil
}

type RetainNetworkInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstIds       []*common.UUID         `protobuf:"bytes,1,rep,name=inst_ids,json=instIds,proto3" json:"inst_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetainNetworkInstanceRequest) Reset() {
	*x = RetainNetworkInstanceRequest{}
	mi := &file_api_manage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetainNetworkInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetainNetworkInstanceRequest) ProtoMessage() {}

func (x *RetainNetworkInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetainNetworkInstanceRequest.ProtoReflect.Descriptor instead.
func (*RetainNetworkInstanceRequest) Descriptor() ([]byte, []int) {
	return file_api_manage_proto_rawDescGZIP(), []int{11}
}

func (x *RetainNetworkInstanceRequest) GetInstIds() []*common.UUID {
	if x != nil {
		return x.InstIds
	}
	return nil
}

type RetainNetworkInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemainInstIds []*common.UUID         `protobuf:"bytes,1,rep,name=remain_inst_ids,json=remainInstIds,proto3" json:"remain_inst_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetainNetworkInstanceResponse) Reset() {
	*x = RetainNetworkInstanceResponse{}
	mi := &file_api_manage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetainNetworkInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetainNetworkInstanceResponse) ProtoMessage() {}

func (x *RetainNetworkInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetainNetworkInstanceResponse.ProtoReflect.Descriptor instead.
func (*RetainNetworkInstanceResponse) Descriptor() ([]byte, []int) {
	return file_api_manage_proto_rawDescGZIP(), []int{12}
}

func (x *RetainNetworkInstanceResponse) GetRemainInstIds() []*common.UUID {
	if x != nil {
		return x.RemainInstIds
	}
	return nil
}

type CollectNetworkInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstIds       []*common.UUID         `protobuf:"bytes,1,rep,name=inst_ids,json=instIds,proto3" json:"inst_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectNetworkInfoRequest) Reset() {
	*x = CollectNetworkInfoRequest{}
	mi := &file_api_manage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectNetworkInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectNetworkInfoRequest) ProtoMessage() {}

func (x *CollectNetworkInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectNetworkInfoRequest.ProtoReflect.Descriptor instead.
func (*CollectNetworkInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_manage_proto_rawDescGZIP(), []int{13}
}

func (x *CollectNetworkInfoRequest) GetInstIds() []*common.UUID {
	if x != nil {
		return x.InstIds
	}
	return nil
}

type CollectNetworkInfoResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Info          *NetworkInstanceRunningInfoMap `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectNetworkInfoResponse) Reset() {
	*x = CollectNetworkInfoResponse{}
	mi := &file_api_manage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectNetworkInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectNetworkInfoResponse) ProtoMessage() {}

func (x *CollectNetworkInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectNetworkInfoResponse.ProtoReflect.Descriptor instead.
func (*CollectNetworkInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_manage_proto_rawDescGZIP(), []int{14}
}

func (x *CollectNetworkInfoResponse) GetInfo() *NetworkInstanceRunningInfoMap {
	if x != nil {
		return x.Info
	}
	return nil
}

type ListNetworkInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNetworkInstanceRequest) Reset() {
	*x = ListNetworkInstanceRequest{}
	mi := &file_api_manage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNetworkInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNetworkInstanceRequest) ProtoMessage() {}

func (x *ListNetworkInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNetworkInstanceRequest.ProtoReflect.Descriptor instead.
func (*ListNetworkInstanceRequest) Descriptor() ([]byte, []int) {
	return file_api_manage_proto_rawDescGZIP(), []int{15}
}

type ListNetworkInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstIds       []*common.UUID         `protobuf:"bytes,1,rep,name=inst_ids,json=instIds,proto3" json:"inst_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNetworkInstanceResponse) Reset() {
	*x = ListNetworkInstanceResponse{}
	mi := &file_api_manage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNetworkInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNetworkInstanceResponse) ProtoMessage() {}

func (x *ListNetworkInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNetworkInstanceResponse.ProtoReflect.Descriptor instead.
func (*ListNetworkInstanceResponse) Descriptor() ([]byte, []int) {
	return file_api_manage_proto_rawDescGZIP(), []int{16}
}

func (x *ListNetworkInstanceResponse) GetInstIds() []*common.UUID {
	if x != nil {
		return x.InstIds
	}
	return nil
}

type DeleteNetworkInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstIds       []*common.UUID         `protobuf:"bytes,1,rep,name=inst_ids,json=instIds,proto3" json:"inst_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNetworkInstanceRequest) Reset() {
	*x = DeleteNetworkInstanceRequest{}
	mi := &file_api_manage_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNetworkInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNetworkInstanceRequest) ProtoMessage() {}

func (x *DeleteNetworkInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNetworkInstanceRequest.ProtoReflect.Descriptor instead.
func (*DeleteNetworkInstanceRequest) Descriptor() ([]byte, []int) {
	return file_api_manage_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteNetworkInstanceRequest) GetInstIds() []*common.UUID {
	if x != nil {
		return x.InstIds
	}
	return nil
}

type DeleteNetworkInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemainInstIds []*common.UUID         `protobuf:"bytes,1,rep,name=remain_inst_ids,json=remainInstIds,proto3" json:"remain_inst_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNetworkInstanceResponse) Reset() {
	*x = DeleteNetworkInstanceResponse{}
	mi := &file_api_manage_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNetworkInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNetworkInstanceResponse) ProtoMessage() {}

func (x *DeleteNetworkInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNetworkInstanceResponse.ProtoReflect.Descriptor instead.
func (*DeleteNetworkInstanceResponse) Descriptor() ([]byte, []int) {
	return file_api_manage_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteNetworkInstanceResponse) GetRemainInstIds() []*common.UUID {
	if x != nil {
		return x.RemainInstIds
	}
	return nil
}

type GetNetworkInstanceConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstId        *common.UUID           `protobuf:"bytes,1,opt,name=inst_id,json=instId,proto3" json:"inst_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworkInstanceConfigRequest) Reset() {
	*x = GetNetworkInstanceConfigRequest{}
	mi := &file_api_manage_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkInstanceConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkInstanceConfigRequest) ProtoMessage() {}

func (x *GetNetworkInstanceConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkInstanceConfigRequest.ProtoReflect.Descriptor instead.
func (*GetNetworkInstanceConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_manage_proto_rawDescGZIP(), []int{19}
}

func (x *GetNetworkInstanceConfigRequest) GetInstId() *common.UUID {
	if x != nil {
		return x.InstId
	}
	return nil
}

type GetNetworkInstanceConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *NetworkConfig         `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Source        ConfigSource           `protobuf:"varint,2,opt,name=source,proto3,enum=api.manage.ConfigSource" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworkInstanceConfigResponse) Reset() {
	*x = GetNetworkInstanceConfigResponse{}
	mi := &file_api_manage_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkInstanceConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkInstanceConfigResponse) ProtoMessage() {}

func (x *GetNetworkInstanceConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkInstanceConfigResponse.ProtoReflect.Descriptor instead.
func (*GetNetworkInstanceConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_manage_proto_rawDescGZIP(), []int{20}
}

func (x *GetNetworkInstanceConfigResponse) GetConfig() *NetworkConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GetNetworkInstanceConfigResponse) GetSource() ConfigSource {
	if x != nil {
		return x.Source
	}
	return ConfigSource_ConfigSourceUnspecified
}

type ListNetworkInstanceMetaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstIds       []*common.UUID         `protobuf:"bytes,1,rep,name=inst_ids,json=instIds,proto3" json:"inst_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNetworkInstanceMetaRequest) Reset() {
	*x = ListNetworkInstanceMetaRequest{}
	mi := &file_api_manage_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNetworkInstanceMetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNetworkInstanceMetaRequest) ProtoMessage() {}

func (x *ListNetworkInstanceMetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNetworkInstanceMetaRequest.ProtoReflect.Descriptor instead.
func (*ListNetworkInstanceMetaRequest) Descriptor() ([]byte, []int) {
	return file_api_manage_proto_rawDescGZIP(), []int{21}
}

func (x *ListNetworkInstanceMetaRequest) GetInstIds() []*common.UUID {
	if x != nil {
		return x.InstIds
	}
	return nil
}

type ListNetworkInstanceMetaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metas         []*NetworkMeta         `protobuf:"bytes,1,rep,name=metas,proto3" json:"metas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNetworkInstanceMetaResponse) Reset() {
	*x = ListNetworkInstanceMetaResponse{}
	mi := &file_api_manage_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNetworkInstanceMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNetworkInstanceMetaResponse) ProtoMessage() {}

func (x *ListNetworkInstanceMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNetworkInstanceMetaResponse.ProtoReflect.Descriptor instead.
func (*ListNetworkInstanceMetaResponse) Descriptor() ([]byte, []int) {
	return file_api_manage_proto_rawDescGZIP(), []int{22}
}

func (x *ListNetworkInstanceMetaResponse) GetMetas() []*NetworkMeta {
	if x != nil {
		return x.Metas
	}
	return nil
}

var File_api_manage_proto protoreflect.FileDescriptor

const file_api_manage_proto_rawDesc = "" +
	"\n" +
	"\x10api_manage.proto\x12\n" +
	"api.manage\x1a\fcommon.proto\x1a\x0epeer_rpc.proto\x1a\x12api_instance.proto\x1a\tacl.proto\"\xef!\n" +
	"\rNetworkConfig\x12$\n" +
	"\vinstance_id\x18\x01 \x01(\tH\x00R\n" +
	"instanceId\x88\x01\x01\x12\x17\n" +
	"\x04dhcp\x18\x02 \x01(\bH\x01R\x04dhcp\x88\x01\x01\x12&\n" +
	"\fvirtual_ipv4\x18\x03 \x01(\tH\x02R\vvirtualIpv4\x88\x01\x01\x12*\n" +
	"\x0enetwork_length\x18\x04 \x01(\x05H\x03R\rnetworkLength\x88\x01\x01\x12\x1f\n" +
	"\bhostname\x18\x05 \x01(\tH\x04R\bhostname\x88\x01\x01\x12&\n" +
	"\fnetwork_name\x18\x06 \x01(\tH\x05R\vnetworkName\x88\x01\x01\x12*\n" +
	"\x0enetwork_secret\x18\a \x01(\tH\x06R\rnetworkSecret\x88\x01\x01\x12N\n" +
	"\x11networking_method\x18\b \x01(\x0e2\x1c.api.manage.NetworkingMethodH\aR\x10networkingMethod\x88\x01\x01\x12/\n" +
	"\x11public_server_url\x18\t \x01(\tH\bR\x0fpublicServerUrl\x88\x01\x01\x12\x1b\n" +
	"\tpeer_urls\x18\n" +
	" \x03(\tR\bpeerUrls\x12\x1f\n" +
	"\vproxy_cidrs\x18\v \x03(\tR\n" +
	"proxyCidrs\x12/\n" +
	"\x11enable_vpn_portal\x18\f \x01(\bH\tR\x0fenableVpnPortal\x88\x01\x01\x128\n" +
	"\x16vpn_portal_listen_port\x18\r \x01(\x05H\n" +
	"R\x13vpnPortalListenPort\x88\x01\x01\x12G\n" +
	"\x1evpn_portal_client_network_addr\x18\x0e \x01(\tH\vR\x1avpnPortalClientNetworkAddr\x88\x01\x01\x12E\n" +
	"\x1dvpn_portal_client_network_len\x18\x0f \x01(\x05H\fR\x19vpnPortalClientNetworkLen\x88\x01\x01\x120\n" +
	"\x11advanced_settings\x18\x10 \x01(\bH\rR\x10advancedSettings\x88\x01\x01\x12#\n" +
	"\rlistener_urls\x18\x11 \x03(\tR\flistenerUrls\x12(\n" +
	"\rlatency_first\x18\x13 \x01(\bH\x0eR\flatencyFirst\x88\x01\x01\x12\x1e\n" +
	"\bdev_name\x18\x14 \x01(\tH\x0fR\adevName\x88\x01\x01\x12$\n" +
	"\vuse_smoltcp\x18\x15 \x01(\bH\x10R\n" +
	"useSmoltcp\x88\x01\x01\x12&\n" +
	"\fdisable_ipv6\x18/ \x01(\bH\x11R\vdisableIpv6\x88\x01\x01\x12-\n" +
	"\x10enable_kcp_proxy\x18\x16 \x01(\bH\x12R\x0eenableKcpProxy\x88\x01\x01\x12/\n" +
	"\x11disable_kcp_input\x18\x17 \x01(\bH\x13R\x0fdisableKcpInput\x88\x01\x01\x12$\n" +
	"\vdisable_p2p\x18\x18 \x01(\bH\x14R\n" +
	"disableP2p\x88\x01\x01\x12$\n" +
	"\vbind_device\x18\x19 \x01(\bH\x15R\n" +
	"bindDevice\x88\x01\x01\x12\x1a\n" +
	"\x06no_tun\x18\x1a \x01(\bH\x16R\x05noTun\x88\x01\x01\x12-\n" +
	"\x10enable_exit_node\x18\x1b \x01(\bH\x17R\x0eenableExitNode\x88\x01\x01\x120\n" +
	"\x12relay_all_peer_rpc\x18\x1c \x01(\bH\x18R\x0frelayAllPeerRpc\x88\x01\x01\x12&\n" +
	"\fmulti_thread\x18\x1d \x01(\bH\x19R\vmultiThread\x88\x01\x01\x12H\n" +
	"\x1eenable_relay_network_whitelist\x18\x1e \x01(\bH\x1aR\x1benableRelayNetworkWhitelist\x88\x01\x01\x126\n" +
	"\x17relay_network_whitelist\x18\x1f \x03(\tR\x15relayNetworkWhitelist\x125\n" +
	"\x14enable_manual_routes\x18  \x01(\bH\x1bR\x12enableManualRoutes\x88\x01\x01\x12\x16\n" +
	"\x06routes\x18! \x03(\tR\x06routes\x12\x1d\n" +
	"\n" +
	"exit_nodes\x18\" \x03(\tR\texitNodes\x12:\n" +
	"\x17proxy_forward_by_system\x18# \x01(\bH\x1cR\x14proxyForwardBySystem\x88\x01\x01\x122\n" +
	"\x12disable_encryption\x18$ \x01(\bH\x1dR\x11disableEncryption\x88\x01\x01\x12(\n" +
	"\renable_socks5\x18% \x01(\bH\x1eR\fenableSocks5\x88\x01\x01\x12$\n" +
	"\vsocks5_port\x18& \x01(\x05H\x1fR\n" +
	"socks5Port\x88\x01\x01\x12>\n" +
	"\x19disable_udp_hole_punching\x18' \x01(\bH R\x16disableUdpHolePunching\x88\x01\x01\x12\x15\n" +
	"\x03mtu\x18( \x01(\x05H!R\x03mtu\x88\x01\x01\x12)\n" +
	"\x10mapped_listeners\x18) \x03(\tR\x0fmappedListeners\x12-\n" +
	"\x10enable_magic_dns\x18* \x01(\bH\"R\x0eenableMagicDns\x88\x01\x01\x123\n" +
	"\x13enable_private_mode\x18+ \x01(\bH#R\x11enablePrivateMode\x88\x01\x01\x12/\n" +
	"\x11enable_quic_proxy\x18- \x01(\bH$R\x0fenableQuicProxy\x88\x01\x01\x121\n" +
	"\x12disable_quic_input\x18. \x01(\bH%R\x10disableQuicInput\x88\x01\x01\x121\n" +
	"\x10quic_listen_port\x182 \x01(\x05B\x02\x18\x01H&R\x0equicListenPort\x88\x01\x01\x12B\n" +
	"\rport_forwards\x180 \x03(\v2\x1d.api.manage.PortForwardConfigR\fportForwards\x12>\n" +
	"\x19disable_sym_hole_punching\x181 \x01(\bH'R\x16disableSymHolePunching\x88\x01\x01\x12\x1e\n" +
	"\bp2p_only\x183 \x01(\bH(R\ap2pOnly\x88\x01\x01\x12L\n" +
	"\x12data_compress_algo\x184 \x01(\x0e2\x19.common.CompressionAlgoPbH)R\x10dataCompressAlgo\x88\x01\x01\x126\n" +
	"\x14encryption_algorithm\x185 \x01(\tH*R\x13encryptionAlgorithm\x88\x01\x01\x12>\n" +
	"\x19disable_tcp_hole_punching\x186 \x01(\bH+R\x16disableTcpHolePunching\x88\x01\x01\x129\n" +
	"\vsecure_mode\x187 \x01(\v2\x18.common.SecureModeConfigR\n" +
	"secureMode\x12\x1f\n" +
	"\x03acl\x188 \x01(\v2\b.acl.AclH,R\x03acl\x88\x01\x01\x12,\n" +
	"\x0fcredential_file\x189 \x01(\tH-R\x0ecredentialFile\x88\x01\x01\x12\x1e\n" +
	"\blazy_p2p\x18: \x01(\bH.R\alazyP2p\x88\x01\x01\x12\x1e\n" +
	"\bneed_p2p\x18; \x01(\bH/R\aneedP2p\x88\x01\x01\x12:\n" +
	"\x17instance_recv_bps_limit\x18< \x01(\x04H0R\x14instanceRecvBpsLimit\x88\x01\x01\x12&\n" +
	"\fdisable_upnp\x18= \x01(\bH1R\vdisableUpnp\x88\x01\x01\x12>\n" +
	"\x19ipv6_public_addr_provider\x18> \x01(\bH2R\x16ipv6PublicAddrProvider\x88\x01\x01\x126\n" +
	"\x15ipv6_public_addr_auto\x18? \x01(\bH3R\x12ipv6PublicAddrAuto\x88\x01\x01\x12:\n" +
	"\x17ipv6_public_addr_prefix\x18@ \x01(\tH4R\x14ipv6PublicAddrPrefix\x88\x01\x01\x121\n" +
	"\x12disable_relay_data\x18A \x01(\bH5R\x10disableRelayData\x88\x01\x01\x12@\n" +
	"\x1aenable_udp_broadcast_relay\x18B \x01(\bH6R\x17enableUdpBroadcastRelay\x88\x01\x01\x12$\n" +
	"\vsocket_mark\x18C \x01(\rH7R\n" +
	"socketMark\x88\x01\x01\x123\n" +
	"\x05peers\x18D \x03(\v2\x1d.api.manage.NetworkPeerConfigR\x05peersB\x0e\n" +
	"\f_instance_idB\a\n" +
	"\x05_dhcpB\x0f\n" +
	"\r_virtual_ipv4B\x11\n" +
	"\x0f_network_lengthB\v\n" +
	"\t_hostnameB\x0f\n" +
	"\r_network_nameB\x11\n" +
	"\x0f_network_secretB\x14\n" +
	"\x12_networking_methodB\x14\n" +
	"\x12_public_server_urlB\x14\n" +
	"\x12_enable_vpn_portalB\x19\n" +
	"\x17_vpn_portal_listen_portB!\n" +
	"\x1f_vpn_portal_client_network_addrB \n" +
	"\x1e_vpn_portal_client_network_lenB\x14\n" +
	"\x12_advanced_settingsB\x10\n" +
	"\x0e_latency_firstB\v\n" +
	"\t_dev_nameB\x0e\n" +
	"\f_use_smoltcpB\x0f\n" +
	"\r_disable_ipv6B\x13\n" +
	"\x11_enable_kcp_proxyB\x14\n" +
	"\x12_disable_kcp_inputB\x0e\n" +
	"\f_disable_p2pB\x0e\n" +
	"\f_bind_deviceB\t\n" +
	"\a_no_tunB\x13\n" +
	"\x11_enable_exit_nodeB\x15\n" +
	"\x13_relay_all_peer_rpcB\x0f\n" +
	"\r_multi_threadB!\n" +
	"\x1f_enable_relay_network_whitelistB\x17\n" +
	"\x15_enable_manual_routesB\x1a\n" +
	"\x18_proxy_forward_by_systemB\x15\n" +
	"\x13_disable_encryptionB\x10\n" +
	"\x0e_enable_socks5B\x0e\n" +
	"\f_socks5_portB\x1c\n" +
	"\x1a_disable_udp_hole_punchingB\x06\n" +
	"\x04_mtuB\x13\n" +
	"\x11_enable_magic_dnsB\x16\n" +
	"\x14_enable_private_modeB\x14\n" +
	"\x12_enable_quic_proxyB\x15\n" +
	"\x13_disable_quic_inputB\x13\n" +
	"\x11_quic_listen_portB\x1c\n" +
	"\x1a_disable_sym_hole_punchingB\v\n" +
	"\t_p2p_onlyB\x15\n" +
	"\x13_data_compress_algoB\x17\n" +
	"\x15_encryption_algorithmB\x1c\n" +
	"\x1a_disable_tcp_hole_punchingB\x06\n" +
	"\x04_aclB\x12\n" +
	"\x10_credential_fileB\v\n" +
	"\t_lazy_p2pB\v\n" +
	"\t_need_p2pB\x1a\n" +
	"\x18_instance_recv_bps_limitB\x0f\n" +
	"\r_disable_upnpB\x1c\n" +
	"\x1a_ipv6_public_addr_providerB\x18\n" +
	"\x16_ipv6_public_addr_autoB\x1a\n" +
	"\x18_ipv6_public_addr_prefixB\x15\n" +
	"\x13_disable_relay_dataB\x1d\n" +
	"\x1b_enable_udp_broadcast_relayB\x0e\n" +
	"\f_socket_mark\"f\n" +
	"\x11NetworkPeerConfig\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12+\n" +
	"\x0fpeer_public_key\x18\x02 \x01(\tH\x00R\rpeerPublicKey\x88\x01\x01B\x12\n" +
	"\x10_peer_public_key\"\x91\x01\n" +
	"\x11PortForwardConfig\x12\x17\n" +
	"\abind_ip\x18\x01 \x01(\tR\x06bindIp\x12\x1b\n" +
	"\tbind_port\x18\x02 \x01(\rR\bbindPort\x12\x15\n" +
	"\x06dst_ip\x18\x03 \x01(\tR\x05dstIp\x12\x19\n" +
	"\bdst_port\x18\x04 \x01(\rR\adstPort\x12\x14\n" +
	"\x05proto\x18\x05 \x01(\tR\x05proto\"\xd7\x02\n" +
	"\n" +
	"MyNodeInfo\x123\n" +
	"\fvirtual_ipv4\x18\x01 \x01(\v2\x10.common.Ipv4InetR\vvirtualIpv4\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12-\n" +
	"\x03ips\x18\x04 \x01(\v2\x1b.peer_rpc.GetIpListResponseR\x03ips\x12-\n" +
	"\tstun_info\x18\x05 \x01(\v2\x10.common.StunInfoR\bstunInfo\x12)\n" +
	"\tlisteners\x18\x06 \x03(\v2\v.common.UrlR\tlisteners\x12)\n" +
	"\x0evpn_portal_cfg\x18\a \x01(\tH\x00R\fvpnPortalCfg\x88\x01\x01\x12\x17\n" +
	"\apeer_id\x18\b \x01(\rR\x06peerIdB\x11\n" +
	"\x0f_vpn_portal_cfg\"\xd3\x03\n" +
	"\x1aNetworkInstanceRunningInfo\x12\x19\n" +
	"\bdev_name\x18\x01 \x01(\tR\adevName\x128\n" +
	"\fmy_node_info\x18\x02 \x01(\v2\x16.api.manage.MyNodeInfoR\n" +
	"myNodeInfo\x12\x16\n" +
	"\x06events\x18\x03 \x03(\tR\x06events\x12+\n" +
	"\x06routes\x18\x04 \x03(\v2\x13.api.instance.RouteR\x06routes\x12,\n" +
	"\x05peers\x18\x05 \x03(\v2\x16.api.instance.PeerInfoR\x05peers\x12E\n" +
	"\x10peer_route_pairs\x18\x06 \x03(\v2\x1b.api.instance.PeerRoutePairR\x0epeerRoutePairs\x12\x18\n" +
	"\arunning\x18\a \x01(\bR\arunning\x12 \n" +
	"\terror_msg\x18\b \x01(\tH\x00R\berrorMsg\x88\x01\x01\x12\\\n" +
	"\x17foreign_network_summary\x18\t \x01(\v2$.peer_rpc.RouteForeignNetworkSummaryR\x15foreignNetworkSummaryB\f\n" +
	"\n" +
	"_error_msg\"\xc5\x01\n" +
	"\x1dNetworkInstanceRunningInfoMap\x12D\n" +
	"\x03map\x18\x01 \x03(\v22.api.manage.NetworkInstanceRunningInfoMap.MapEntryR\x03map\x1a^\n" +
	"\bMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12<\n" +
	"\x05value\x18\x02 \x01(\v2&.api.manage.NetworkInstanceRunningInfoR\x05value:\x028\x01\"\xdb\x01\n" +
	"\vNetworkMeta\x12%\n" +
	"\ainst_id\x18\x01 \x01(\v2\f.common.UUIDR\x06instId\x12!\n" +
	"\fnetwork_name\x18\x02 \x01(\tR\vnetworkName\x12+\n" +
	"\x11config_permission\x18\x03 \x01(\rR\x10configPermission\x12#\n" +
	"\rinstance_name\x18\x04 \x01(\tR\finstanceName\x120\n" +
	"\x06source\x18\x05 \x01(\x0e2\x18.api.manage.ConfigSourceR\x06source\"J\n" +
	"\x15ValidateConfigRequest\x121\n" +
	"\x06config\x18\x01 \x01(\v2\x19.api.manage.NetworkConfigR\x06config\"9\n" +
	"\x16ValidateConfigResponse\x12\x1f\n" +
	"\vtoml_config\x18\x01 \x01(\tR\n" +
	"tomlConfig\"\xc5\x01\n" +
	"\x19RunNetworkInstanceRequest\x12%\n" +
	"\ainst_id\x18\x01 \x01(\v2\f.common.UUIDR\x06instId\x121\n" +
	"\x06config\x18\x02 \x01(\v2\x19.api.manage.NetworkConfigR\x06config\x12\x1c\n" +
	"\toverwrite\x18\x03 \x01(\bR\toverwrite\x120\n" +
	"\x06source\x18\x04 \x01(\x0e2\x18.api.manage.ConfigSourceR\x06source\"C\n" +
	"\x1aRunNetworkInstanceResponse\x12%\n" +
	"\ainst_id\x18\x01 \x01(\v2\f.common.UUIDR\x06instId\"G\n" +
	"\x1cRetainNetworkInstanceRequest\x12'\n" +
	"\binst_ids\x18\x01 \x03(\v2\f.common.UUIDR\ainstIds\"U\n" +
	"\x1dRetainNetworkInstanceResponse\x124\n" +
	"\x0fremain_inst_ids\x18\x01 \x03(\v2\f.common.UUIDR\rremainInstIds\"D\n" +
	"\x19CollectNetworkInfoRequest\x12'\n" +
	"\binst_ids\x18\x01 \x03(\v2\f.common.UUIDR\ainstIds\"[\n" +
	"\x1aCollectNetworkInfoResponse\x12=\n" +
	"\x04info\x18\x01 \x01(\v2).api.manage.NetworkInstanceRunningInfoMapR\x04info\"\x1c\n" +
	"\x1aListNetworkInstanceRequest\"F\n" +
	"\x1bListNetworkInstanceResponse\x12'\n" +
	"\binst_ids\x18\x01 \x03(\v2\f.common.UUIDR\ainstIds\"G\n" +
	"\x1cDeleteNetworkInstanceRequest\x12'\n" +
	"\binst_ids\x18\x01 \x03(\v2\f.common.UUIDR\ainstIds\"U\n" +
	"\x1dDeleteNetworkInstanceResponse\x124\n" +
	"\x0fremain_inst_ids\x18\x01 \x03(\v2\f.common.UUIDR\rremainInstIds\"H\n" +
	"\x1fGetNetworkInstanceConfigRequest\x12%\n" +
	"\ainst_id\x18\x01 \x01(\v2\f.common.UUIDR\x06instId\"\x87\x01\n" +
	" GetNetworkInstanceConfigResponse\x121\n" +
	"\x06config\x18\x01 \x01(\v2\x19.api.manage.NetworkConfigR\x06config\x120\n" +
	"\x06source\x18\x02 \x01(\x0e2\x18.api.manage.ConfigSourceR\x06source\"I\n" +
	"\x1eListNetworkInstanceMetaRequest\x12'\n" +
	"\binst_ids\x18\x01 \x03(\v2\f.common.UUIDR\ainstIds\"P\n" +
	"\x1fListNetworkInstanceMetaResponse\x12-\n" +
	"\x05metas\x18\x01 \x03(\v2\x17.api.manage.NetworkMetaR\x05metas*@\n" +
	"\x10NetworkingMethod\x12\x10\n" +
	"\fPublicServer\x10\x00\x12\n" +
	"\n" +
	"\x06Manual\x10\x01\x12\x0e\n" +
	"\n" +
	"Standalone\x10\x02*V\n" +
	"\fConfigSource\x12\x1b\n" +
	"\x17ConfigSourceUnspecified\x10\x00\x12\x14\n" +
	"\x10ConfigSourceUser\x10\x01\x12\x13\n" +
	"\x0fConfigSourceWeb\x10\x022\xf4\x06\n" +
	"\x10WebClientService\x12Y\n" +
	"\x0eValidateConfig\x12!.api.manage.ValidateConfigRequest\x1a\".api.manage.ValidateConfigResponse\"\x00\x12e\n" +
	"\x12RunNetworkInstance\x12%.api.manage.RunNetworkInstanceRequest\x1a&.api.manage.RunNetworkInstanceResponse\"\x00\x12n\n" +
	"\x15RetainNetworkInstance\x12(.api.manage.RetainNetworkInstanceRequest\x1a).api.manage.RetainNetworkInstanceResponse\"\x00\x12e\n" +
	"\x12CollectNetworkInfo\x12%.api.manage.CollectNetworkInfoRequest\x1a&.api.manage.CollectNetworkInfoResponse\"\x00\x12h\n" +
	"\x13ListNetworkInstance\x12&.api.manage.ListNetworkInstanceRequest\x1a'.api.manage.ListNetworkInstanceResponse\"\x00\x12n\n" +
	"\x15DeleteNetworkInstance\x12(.api.manage.DeleteNetworkInstanceRequest\x1a).api.manage.DeleteNetworkInstanceResponse\"\x00\x12w\n" +
	"\x18GetNetworkInstanceConfig\x12+.api.manage.GetNetworkInstanceConfigRequest\x1a,.api.manage.GetNetworkInstanceConfigResponse\"\x00\x12t\n" +
	"\x17ListNetworkInstanceMeta\x12*.api.manage.ListNetworkInstanceMetaRequest\x1a+.api.manage.ListNetworkInstanceMetaResponse\"\x00b\x06proto3"

var (
	file_api_manage_proto_rawDescOnce sync.Once
	file_api_manage_proto_rawDescData []byte
)

func file_api_manage_proto_rawDescGZIP() []byte {
	file_api_manage_proto_rawDescOnce.Do(func() {
		file_api_manage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_manage_proto_rawDesc), len(file_api_manage_proto_rawDesc)))
	})
	return file_api_manage_proto_rawDescData
}

var file_api_manage_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_manage_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_api_manage_proto_goTypes = []any{
	(NetworkingMethod)(0),                       // 0: api.manage.NetworkingMethod
	(ConfigSource)(0),                           // 1: api.manage.ConfigSource
	(*NetworkConfig)(nil),                       // 2: api.manage.NetworkConfig
	(*NetworkPeerConfig)(nil),                   // 3: api.manage.NetworkPeerConfig
	(*PortForwardConfig)(nil),                   // 4: api.manage.PortForwardConfig
	(*MyNodeInfo)(nil),                          // 5: api.manage.MyNodeInfo
	(*NetworkInstanceRunningInfo)(nil),          // 6: api.manage.NetworkInstanceRunningInfo
	(*NetworkInstanceRunningInfoMap)(nil),       // 7: api.manage.NetworkInstanceRunningInfoMap
	(*NetworkMeta)(nil),                         // 8: api.manage.NetworkMeta
	(*ValidateConfigRequest)(nil),               // 9: api.manage.ValidateConfigRequest
	(*ValidateConfigResponse)(nil),              // 10: api.manage.ValidateConfigResponse
	(*RunNetworkInstanceRequest)(nil),           // 11: api.manage.RunNetworkInstanceRequest
	(*RunNetworkInstanceResponse)(nil),          // 12: api.manage.RunNetworkInstanceResponse
	(*RetainNetworkInstanceRequest)(nil),        // 13: api.manage.RetainNetworkInstanceRequest
	(*RetainNetworkInstanceResponse)(nil),       // 14: api.manage.RetainNetworkInstanceResponse
	(*CollectNetworkInfoRequest)(nil),           // 15: api.manage.CollectNetworkInfoRequest
	(*CollectNetworkInfoResponse)(nil),          // 16: api.manage.CollectNetworkInfoResponse
	(*ListNetworkInstanceRequest)(nil),          // 17: api.manage.ListNetworkInstanceRequest
	(*ListNetworkInstanceResponse)(nil),         // 18: api.manage.ListNetworkInstanceResponse
	(*DeleteNetworkInstanceRequest)(nil),        // 19: api.manage.DeleteNetworkInstanceRequest
	(*DeleteNetworkInstanceResponse)(nil),       // 20: api.manage.DeleteNetworkInstanceResponse
	(*GetNetworkInstanceConfigRequest)(nil),     // 21: api.manage.GetNetworkInstanceConfigRequest
	(*GetNetworkInstanceConfigResponse)(nil),    // 22: api.manage.GetNetworkInstanceConfigResponse
	(*ListNetworkInstanceMetaRequest)(nil),      // 23: api.manage.ListNetworkInstanceMetaRequest
	(*ListNetworkInstanceMetaResponse)(nil),     // 24: api.manage.ListNetworkInstanceMetaResponse
	nil,                                         // 25: api.manage.NetworkInstanceRunningInfoMap.MapEntry
	(common.CompressionAlgoPb)(0),               // 26: common.CompressionAlgoPb
	(*common.SecureModeConfig)(nil),             // 27: common.SecureModeConfig
	(*acl.Acl)(nil),                             // 28: acl.Acl
	(*common.Ipv4Inet)(nil),                     // 29: common.Ipv4Inet
	(*peer_rpc.GetIpListResponse)(nil),          // 30: peer_rpc.GetIpListResponse
	(*common.StunInfo)(nil),                     // 31: common.StunInfo
	(*common.Url)(nil),                          // 32: common.Url
	(*instance.Route)(nil),                      // 33: api.instance.Route
	(*instance.PeerInfo)(nil),                   // 34: api.instance.PeerInfo
	(*instance.PeerRoutePair)(nil),              // 35: api.instance.PeerRoutePair
	(*peer_rpc.RouteForeignNetworkSummary)(nil), // 36: peer_rpc.RouteForeignNetworkSummary
	(*common.UUID)(nil),                         // 37: common.UUID
}
var file_api_manage_proto_depIdxs = []int32{
	0,  // 0: api.manage.NetworkConfig.networking_method:type_name -> api.manage.NetworkingMethod
	4,  // 1: api.manage.NetworkConfig.port_forwards:type_name -> api.manage.PortForwardConfig
	26, // 2: api.manage.NetworkConfig.data_compress_algo:type_name -> common.CompressionAlgoPb
	27, // 3: api.manage.NetworkConfig.secure_mode:type_name -> common.SecureModeConfig
	28, // 4: api.manage.NetworkConfig.acl:type_name -> acl.Acl
	3,  // 5: api.manage.NetworkConfig.peers:type_name -> api.manage.NetworkPeerConfig
	29, // 6: api.manage.MyNodeInfo.virtual_ipv4:type_name -> common.Ipv4Inet
	30, // 7: api.manage.MyNodeInfo.ips:type_name -> peer_rpc.GetIpListResponse
	31, // 8: api.manage.MyNodeInfo.stun_info:type_name -> common.StunInfo
	32, // 9: api.manage.MyNodeInfo.listeners:type_name -> common.Url
	5,  // 10: api.manage.NetworkInstanceRunningInfo.my_node_info:type_name -> api.manage.MyNodeInfo
	33, // 11: api.manage.NetworkInstanceRunningInfo.routes:type_name -> api.instance.Route
	34, // 12: api.manage.NetworkInstanceRunningInfo.peers:type_name -> api.instance.PeerInfo
	35, // 13: api.manage.NetworkInstanceRunningInfo.peer_route_pairs:type_name -> api.instance.PeerRoutePair
	36, // 14: api.manage.NetworkInstanceRunningInfo.foreign_network_summary:type_name -> peer_rpc.RouteForeignNetworkSummary
	25, // 15: api.manage.NetworkInstanceRunningInfoMap.map:type_name -> api.manage.NetworkInstanceRunningInfoMap.MapEntry
	37, // 16: api.manage.NetworkMeta.inst_id:type_name -> common.UUID
	1,  // 17: api.manage.NetworkMeta.source:type_name -> api.manage.ConfigSource
	2,  // 18: api.manage.ValidateConfigRequest.config:type_name -> api.manage.NetworkConfig
	37, // 19: api.manage.RunNetworkInstanceRequest.inst_id:type_name -> common.UUID
	2,  // 20: api.manage.RunNetworkInstanceRequest.config:type_name -> api.manage.NetworkConfig
	1,  // 21: api.manage.RunNetworkInstanceRequest.source:type_name -> api.manage.ConfigSource
	37, // 22: api.manage.RunNetworkInstanceResponse.inst_id:type_name -> common.UUID
	37, // 23: api.manage.RetainNetworkInstanceRequest.inst_ids:type_name -> common.UUID
	37, // 24: api.manage.RetainNetworkInstanceResponse.remain_inst_ids:type_name -> common.UUID
	37, // 25: api.manage.CollectNetworkInfoRequest.inst_ids:type_name -> common.UUID
	7,  // 26: api.manage.CollectNetworkInfoResponse.info:type_name -> api.manage.NetworkInstanceRunningInfoMap
	37, // 27: api.manage.ListNetworkInstanceResponse.inst_ids:type_name -> common.UUID
	37, // 28: api.manage.DeleteNetworkInstanceRequest.inst_ids:type_name -> common.UUID
	37, // 29: api.manage.DeleteNetworkInstanceResponse.remain_inst_ids:type_name -> common.UUID
	37, // 30: api.manage.GetNetworkInstanceConfigRequest.inst_id:type_name -> common.UUID
	2,  // 31: api.manage.GetNetworkInstanceConfigResponse.config:type_name -> api.manage.NetworkConfig
	1,  // 32: api.manage.GetNetworkInstanceConfigResponse.source:type_name -> api.manage.ConfigSource
	37, // 33: api.manage.ListNetworkInstanceMetaRequest.inst_ids:type_name -> common.UUID
	8,  // 34: api.manage.ListNetworkInstanceMetaResponse.metas:type_name -> api.manage.NetworkMeta
	6,  // 35: api.manage.NetworkInstanceRunningInfoMap.MapEntry.value:type_name -> api.manage.NetworkInstanceRunningInfo
	9,  // 36: api.manage.WebClientService.ValidateConfig:input_type -> api.manage.ValidateConfigRequest
	11, // 37: api.manage.WebClientService.RunNetworkInstance:input_type -> api.manage.RunNetworkInstanceRequest
	13, // 38: api.manage.WebClientService.RetainNetworkInstance:input_type -> api.manage.RetainNetworkInstanceRequest
	15, // 39: api.manage.WebClientService.CollectNetworkInfo:input_type -> api.manage.CollectNetworkInfoRequest
	17, // 40: api.manage.WebClientService.ListNetworkInstance:input_type -> api.manage.ListNetworkInstanceRequest
	19, // 41: api.manage.WebClientService.DeleteNetworkInstance:input_type -> api.manage.DeleteNetworkInstanceRequest
	21, // 42: api.manage.WebClientService.GetNetworkInstanceConfig:input_type -> api.manage.GetNetworkInstanceConfigRequest
	23, // 43: api.manage.WebClientService.ListNetworkInstanceMeta:input_type -> api.manage.ListNetworkInstanceMetaRequest
	10, // 44: api.manage.WebClientService.ValidateConfig:output_type -> api.manage.ValidateConfigResponse
	12, // 45: api.manage.WebClientService.RunNetworkInstance:output_type -> api.manage.RunNetworkInstanceResponse
	14, // 46: api.manage.WebClientService.RetainNetworkInstance:output_type -> api.manage.RetainNetworkInstanceResponse
	16, // 47: api.manage.WebClientService.CollectNetworkInfo:output_type -> api.manage.CollectNetworkInfoResponse
	18, // 48: api.manage.WebClientService.ListNetworkInstance:output_type -> api.manage.ListNetworkInstanceResponse
	20, // 49: api.manage.WebClientService.DeleteNetworkInstance:output_type -> api.manage.DeleteNetworkInstanceResponse
	22, // 50: api.manage.WebClientService.GetNetworkInstanceConfig:output_type -> api.manage.GetNetworkInstanceConfigResponse
	24, // 51: api.manage.WebClientService.ListNetworkInstanceMeta:output_type -> api.manage.ListNetworkInstanceMetaResponse
	44, // [44:52] is the sub-list for method output_type
	36, // [36:44] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_api_manage_proto_init() }
func file_api_manage_proto_init() {
	if File_api_manage_proto != nil {
		return
	}
	file_api_manage_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_manage_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_manage_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_manage_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_manage_proto_rawDesc), len(file_api_manage_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_manage_proto_goTypes,
		DependencyIndexes: file_api_manage_proto_depIdxs,
		EnumInfos:         file_api_manage_proto_enumTypes,
		MessageInfos:      file_api_manage_proto_msgTypes,
	}.Build()
	File_api_manage_proto = out.File
	file_api_manage_proto_goTypes = nil
	file_api_manage_proto_depIdxs = nil
}
