packages:
  - 'easytier-web/frontend'
  - 'easytier-web/frontend-lib'
  - 'easytier-gui'
  - 'tauri-plugin-vpnservice'

overrides:
  minimatch: 10.2.4

allowBuilds:
  esbuild: true
  unrs-resolver: true
  vue-demi: true
