[package]
name = "easytier-gui"
version = "2.7.0"
description = "EasyTier GUI"
authors = ["you"]
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]


[dependencies]
# wry 0.47 may crash on android, see https://github.com/EasyTier/EasyTier/issues/527
tauri = { workspace = true, features = [
    "tray-icon",
    "image-png",
    "image-ico",
    "devtools",
] }

serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

easytier = { workspace = true, default-features = true }
easytier-core = { workspace = true, default-features = true }
tokio = { workspace = true, default-features = true, features = ["full"] }
anyhow.workspace = true

once_cell.workspace = true
dashmap.workspace = true


tauri-plugin-shell = "2.3.6"
tauri-plugin-process = "2.3.1"
tauri-plugin-clipboard-manager = "2.3.3"
tauri-plugin-vpnservice = { path = "../../tauri-plugin-vpnservice" }
tauri-plugin-os = "2.3.2"

uuid.workspace = true
async-trait.workspace = true

url = { workspace = true, features = ["serde"] }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.62", features = ["Win32_Foundation", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging"] }
winapi = { workspace = true, features = ["securitybaseapi", "processthreadsapi"] }

[target.'cfg(target_family = "unix")'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "macos")'.dependencies]
security-framework-sys = "2.17.0"


[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }
thunk-rs = { workspace = true, features = [
    "win7",
] }


[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-single-instance = "2.4.4"

[package.metadata.cargo-machete]
ignored = [
    # Called by build.rs; thunk is only used on Windows.
    "tauri-build",
    "thunk-rs",
]
