[package]
name = "easytier-cni"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license-file = "../../easytier/LICENSE"
description = "EasyTier secondary CNI plugin"

[[bin]]
name = "easytier-cni"
path = "src/main.rs"

[dependencies]
anyhow = "1"
easytier = { path = "../../easytier", default-features = false, features = ["zstd"] }
network-interface = "2"
pnet = "0.35"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
tokio = { version = "1", features = ["macros", "rt", "time"] }
url = "2"
uuid = "1"

[dev-dependencies]
tempfile = "3"
