// Code generated by go generate; DO NOT EDIT.

package artifact

const (
	Commit = "63519db2b5f2a6a1b9b7f20905f036dab54eb829"
	SHA256 = "8b82f37d62fba2ffe8e256386096fddf448d4261d51c495d5bd97cd11bbb24a0"
)
