// Code generated by go generate; DO NOT EDIT.

package artifact

const (
	Commit = "dc7d4c30bbf2eee6f3b34d16f937af6cb98db432"
	SHA256 = "7b433b4057d8f1e348b09fff06a8f9ac085659198f0496d1b7837d948537e549"
)
