//! Linux DNS configuration for MagicDNS.
//!
//! Two-tier strategy, modelled on how Tailscale's `net/dns` handles Linux:
//!
//! 1. **systemd-resolved via D-Bus** (`org.freedesktop.resolve1`) when the
//!    system actually runs it — this gives per-link split DNS through
//!    `SetLinkDNS` / `SetLinkDomains`, which is what `resolvectl` itself
//!    would configure.
//! 2. **Direct `/etc/resolv.conf` management** otherwise (Alpine, Gentoo with
//!    OpenRC, or any Linux without systemd-resolved). The original file is
//!    backed up, an easytier-owned file is written atomically, and `close()`
//!    restores the backup.
//!
//! No shell commands are used anywhere on this path.

use std::{
    fs,
    io::{self, Write},
};

use nix::libc;

use super::{OSConfig, SystemConfig};

/// systemd-resolved D-Bus constants.
const RESOLVE1_SERVICE: &str = "org.freedesktop.resolve1";
const RESOLVE1_PATH: &str = "/org/freedesktop/resolve1";
const RESOLVE1_MANAGER_IFACE: &str = "org.freedesktop.resolve1.Manager";

const ETC_RESOLV_CONF: &str = "/etc/resolv.conf";
const RESOLV_CONF_BACKUP: &str = "/etc/resolv.conf.easytier.bak";
/// Marker identifying an easytier-owned resolv.conf.
const RESOLV_CONF_HEADER: &str = "# generated by easytier\n";
/// systemd-resolved stub address; resolv.conf pointing here means resolved
/// owns the resolver (and will rewrite the file if we touch it).
const RESOLVED_STUB: &str = "127.0.0.53";

#[derive(Default)]
pub struct LinuxSystemConfig {}

impl LinuxSystemConfig {
    pub fn new() -> Self {
        LinuxSystemConfig {}
    }

    /// Resolve a network interface name to its kernel ifindex.
    fn interface_index(name: &str) -> io::Result<i32> {
        let c_name = std::ffi::CString::new(name)
            .map_err(|_| io::Error::new(io::ErrorKind::InvalidInput, "invalid interface name"))?;
        // SAFETY: if_nametoindex only reads the NUL-terminated name.
        let idx = unsafe { libc::if_nametoindex(c_name.as_ptr()) };
        if idx == 0 {
            Err(io::Error::last_os_error())
        } else {
            Ok(idx as i32)
        }
    }

    /// Whether the system actually runs systemd-resolved.
    ///
    /// A successful D-Bus *connection* only proves a bus exists — the
    /// `org.freedesktop.resolve1` service may still be absent. Probe the
    /// service itself with the mandatory `org.freedesktop.DBus.Peer.Ping`
    /// method (every object on the bus implements it, so a reply proves the
    /// resolve1 service is registered and running).
    fn resolved_available() -> bool {
        let conn = match zbus::blocking::Connection::system() {
            Ok(c) => c,
            Err(_) => return false,
        };
        conn.call_method(
            Some(RESOLVE1_SERVICE),
            RESOLVE1_PATH,
            Some("org.freedesktop.DBus.Peer"),
            "Ping",
            &(),
        )
        .is_ok()
    }

    fn resolv_conf_points_at_stub() -> bool {
        match fs::read_to_string(ETC_RESOLV_CONF) {
            Ok(content) => content
                .lines()
                .any(|l| l.trim().starts_with("nameserver") && l.contains(RESOLVED_STUB)),
            Err(_) => false,
        }
    }

    fn owned_by_easytier() -> bool {
        match fs::read_to_string(ETC_RESOLV_CONF) {
            Ok(content) => content.starts_with(RESOLV_CONF_HEADER),
            Err(_) => false,
        }
    }

    /// Write bytes to `path` atomically where possible.
    ///
    /// Prefers write-tmp-then-rename; falls back to a plain truncating write
    /// when rename fails (bind-mounted `/etc/resolv.conf` in containers).
    fn atomic_write(path: &str, content: &[u8]) -> io::Result<()> {
        let tmp = format!("{path}.easytier.tmp");
        {
            let mut f = fs::File::create(&tmp)?;
            f.write_all(content)?;
        }
        match fs::rename(&tmp, path) {
            Ok(()) => Ok(()),
            Err(e) if e.kind() == io::ErrorKind::CrossesDevices => {
                // resolv.conf is bind-mounted (containers): can't rename over
                // it without breaking the mount, so truncate in place.
                let mut f = fs::File::create(path)?;
                f.write_all(content)?;
                let _ = fs::remove_file(&tmp);
                Ok(())
            }
            Err(e) => {
                let _ = fs::remove_file(&tmp);
                Err(e)
            }
        }
    }

    /// Direct mode: back up the current resolv.conf (unless it is already
    /// easytier-owned) and write an easytier-owned file with the given
    /// nameservers and search domains.
    fn write_direct(cfg: &OSConfig) -> io::Result<()> {
        if !Self::owned_by_easytier() {
            match fs::copy(ETC_RESOLV_CONF, RESOLV_CONF_BACKUP) {
                Ok(_) => {}
                Err(e) if e.kind() == io::ErrorKind::NotFound => {}
                Err(e) => return Err(e),
            }
        }

        let mut content = String::from(RESOLV_CONF_HEADER);
        for ns in &cfg.nameservers {
            content.push_str(&format!("nameserver {ns}\n"));
        }
        // resolv.conf has no per-domain routing: merge search + match domains
        // into a single search list, deduplicated (darwin's /etc/resolver
        // split-DNS has no Linux equivalent here).
        let mut domains: Vec<String> = cfg
            .search_domains
            .iter()
            .chain(cfg.match_domains.iter())
            .map(|d| d.trim_end_matches('.').to_string())
            .collect();
        domains.dedup();
        if !domains.is_empty() {
            content.push_str(&format!("search {}\n", domains.join(" ")));
        }
        Self::atomic_write(ETC_RESOLV_CONF, content.as_bytes())
    }

    /// Direct mode: restore the backup only if we still own resolv.conf
    /// (never clobber changes the user or another service made meanwhile).
    fn restore_direct() -> io::Result<()> {
        let backup = match fs::read(RESOLV_CONF_BACKUP) {
            Ok(b) => b,
            Err(e) if e.kind() == io::ErrorKind::NotFound => return Ok(()),
            Err(e) => return Err(e),
        };
        if Self::owned_by_easytier() {
            Self::atomic_write(ETC_RESOLV_CONF, &backup)?;
        }
        let _ = fs::remove_file(RESOLV_CONF_BACKUP);
        Ok(())
    }

    /// Set the per-link DNS servers and search/routing domains through the
    /// systemd-resolved Manager D-Bus interface.
    ///
    /// `match_domains` are installed as routing domains (`~zone` in
    /// resolvectl terms) so only those queries go to the MagicDNS server.
    fn apply_link_config(
        &self,
        ifname: &str,
        nameservers: &[String],
        domains: &[String],
    ) -> io::Result<()> {
        let ifindex = Self::interface_index(ifname)?;
        let conn = zbus::blocking::Connection::system()
            .map_err(|e| io::Error::new(io::ErrorKind::Other, format!("D-Bus: {e}")))?;

        if !nameservers.is_empty() {
            let ns: Vec<(i32, Vec<u8>)> = nameservers
                .iter()
                .filter_map(|s| s.parse::<std::net::Ipv4Addr>().ok())
                .map(|ip| (libc::AF_INET as i32, ip.octets().to_vec()))
                .collect();
            if !ns.is_empty() {
                // resolve1.Manager.SetLinkDNS(ifindex, a(iay) addresses)
                let reply = conn.call_method(
                    Some(RESOLVE1_SERVICE),
                    RESOLVE1_PATH,
                    Some(RESOLVE1_MANAGER_IFACE),
                    "SetLinkDNS",
                    &(ifindex, ns),
                );
                if let Err(e) = reply {
                    tracing::warn!("SetLinkDNS failed: {e}");
                }
            }
        }

        if !domains.is_empty() {
            let doms: Vec<(String, bool)> = domains
                .iter()
                .map(|d| (d.trim_end_matches('.').to_string(), true))
                .collect();
            let reply = conn.call_method(
                Some(RESOLVE1_SERVICE),
                RESOLVE1_PATH,
                Some(RESOLVE1_MANAGER_IFACE),
                "SetLinkDomains",
                &(ifindex, doms),
            );
            if let Err(e) = reply {
                tracing::warn!("SetLinkDomains failed: {e}");
            }
        }

        Ok(())
    }
}

impl SystemConfig for LinuxSystemConfig {
    fn set_dns(&self, cfg: &OSConfig) -> io::Result<()> {
        // If no explicit interface was captured, fall back to the default
        // route interface so the DNS config still lands somewhere useful.
        let ifname = match &cfg.interface_name {
            Some(n) => n.clone(),
            None => {
                tracing::warn!("no interface name for DNS config, skipping");
                return Ok(());
            }
        };

        // Prefer systemd-resolved when present; it keeps split DNS working
        // and survives resolv.conf being regenerated by the OS. Otherwise
        // (Alpine, Gentoo+OpenRC, ...) manage /etc/resolv.conf directly.
        if Self::resolved_available() {
            tracing::info!("configuring MagicDNS via systemd-resolved (D-Bus)");
            self.apply_link_config(&ifname, &cfg.nameservers, &cfg.search_domains)
        } else {
            if Self::resolv_conf_points_at_stub() {
                // resolv.conf points at the resolved stub but the service is
                // not running: direct mode will still work (nothing rewrites
                // the file), but note the system state for the user.
                tracing::warn!("resolv.conf references systemd-resolved stub but systemd-resolved is not running");
            }
            tracing::info!(
                "systemd-resolved not available, configuring MagicDNS via {ETC_RESOLV_CONF}"
            );
            Self::write_direct(cfg)
        }
    }

    fn close(&self) -> io::Result<()> {
        Self::restore_direct()
    }
}
