[package]
name = "easytier-ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
easytier = { path = "../../easytier" }

once_cell = "1.18.0"
dashmap = "6.0"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
