[package]
name = "easytier-android-jni"
version = "0.1.0"
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.21"
once_cell.workspace = true
log.workspace = true
android_logger = "0.13"
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
easytier = { workspace = true, default-features = true }
easytier-ffi.workspace = true
