//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::health_records::Entity as HealthRecords;
pub use super::node_tags::Entity as NodeTags;
pub use super::shared_nodes::Entity as SharedNodes;
