name: OpenHarmony

on:
  push:
    branches: ["develop", "main", "releases/**"]
  pull_request:
    branches: ["develop", "main"]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    # necessary for windows
    shell: bash

jobs:
  setup-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup OpenHarmony SDK (5.1.0 Native only)
        uses: openharmony-rs/setup-ohos-sdk@v0.2
        with:
          version: "5.1.0"
          components: "native"

      - name: Prepare SDK Directory
        run: |
          sudo mkdir -p /usr/local/ohos-sdk/linux/native
          echo "Target directory created: /usr/local/ohos-sdk/linux/native"

      - name: Download and Extract Custom SDK
        run: |
          wget https://github.com/FrankHan052176/Easytier-OHOS-sdk/releases/download/v1/ohos-sdk.zip -O /tmp/ohos-sdk.zip
          sudo unzip -o /tmp/ohos-sdk.zip -d /tmp/custom-sdk
          sudo cp -rf /tmp/custom-sdk/linux/native/* /usr/local/ohos-sdk/linux/native/
          echo "Custom SDK files deployed to /usr/local/ohos-sdk/linux/native"
        
      - name: Move Native SDK to /usr/local/ohos-sdk/linux/native
        run: |
          echo "Detected Native SDK path: $OHOS_SDK_NATIVE"
          sudo cp -r "$OHOS_SDK_NATIVE" /usr/local/ohos-sdk/linux/native
          echo "Native SDK moved to /usr/local/ohos-sdk/linux/native"

      - name: Verify SDK
        run: |
          ls -la /usr/local/ohos-sdk/linux/native/sysroot/usr

      - name: Debug Paths
        working-directory: ${{ github.workspace }}
        run: |
          echo "Current directory: $(pwd)"
          ls -la .

      - name: Build
        env:
          OHOS_SDK_PATH: /usr/local/ohos-sdk/linux
          OHOS_TOOLCHAIN_DIR: ${{ env.OHOS_SDK_PATH }}/native/llvm
          TARGET_ARCH: aarch64-linux-ohos
          OHOS_SYSROOT: ${{ env.OHOS_SDK_PATH }}/native/sysroot
          CC: ${{ env.OHOS_TOOLCHAIN_DIR }}/bin/aarch64-unknown-linux-ohos-clang
          CXX: ${{ env.OHOS_TOOLCHAIN_DIR }}/bin/aarch64-unknown-linux-ohos-clang++
          AS: ${{ env.OHOS_TOOLCHAIN_DIR }}/bin/llvm-as
          AR: ${{ env.OHOS_TOOLCHAIN_DIR }}/bin/llvm-ar
          LD: ${{ env.OHOS_TOOLCHAIN_DIR }}/bin/ld.lld
          RANLIB: ${{ env.OHOS_TOOLCHAIN_DIR }}/bin/llvm-ranlib
          STRIP: ${{ env.OHOS_TOOLCHAIN_DIR }}/bin/llvm-strip
          OBJDUMP: ${{ env.OHOS_TOOLCHAIN_DIR }}/bin/llvm-objdump
          OBJCOPY: ${{ env.OHOS_TOOLCHAIN_DIR }}/bin/llvm-objcopy
          NM: ${{ env.OHOS_TOOLCHAIN_DIR }}/bin/llvm-nm
          CFLAGS: -fPIC -D__MUSL__=1 -march=armv8-a --target=${{ env.TARGET_ARCH }} -Wno-error --sysroot=${{ env.OHOS_SYSROOT }} -I${{ env.OHOS_SYSROOT }}/usr/include/${{ env.TARGET_ARCH }}
          CXXFLAGS: ${{ env.CFLAGS }}
          LDFLAGS: --sysroot=${{ env.OHOS_SYSROOT }} -L${{ env.OHOS_SYSROOT }}/usr/lib/${{ env.TARGET_ARCH }} -fuse-ld=${{ env.LD }}
          PKG_CONFIG_PATH: ${{ env.OHOS_SYSROOT }}/usr/lib/pkgconfig:${{ env.OHOS_SYSROOT }}/usr/local/lib/pkgconfig
          PKG_CONFIG_LIBDIR: ${{ env.OHOS_SYSROOT }}/usr/lib:${{ env.OHOS_SYSROOT }}/usr/local/lib
          PKG_CONFIG_SYSROOT_DIR: ${{ env.OHOS_SYSROOT }}
          HOST_TRIPLET: ${{ env.TARGET_ARCH }}
          PATH: ${{ env.OHOS_TOOLCHAIN_DIR }}/bin:${{ env.PATH }}
        working-directory: ${{ github.workspace }}/easytier-contrib/easytier-ohrs
        run: |
          bash ${{ github.workspace }}/.github/workflows/install_rust.sh
          cargo install ohrs
          rustup target add aarch64-unknown-linux-ohos
          ohrs doctor
          ohrs build --release --arch aarch
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: easytier-ohos
          path: ./easytier-contrib/easytier-ohrs/dist/arm64-v8a/libeasytier_ohrs.so
