name: OpenHarmony

on:
  push:
    branches: ["develop", "main", "releases/**"]
  pull_request:
    branches: ["develop", "main"]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    # necessary for windows
    shell: bash

jobs:
  pre_job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      # do not skip push on branch starts with releases/
      should_skip: ${{ steps.skip_check.outputs.should_skip == 'true' && !startsWith(github.ref_name, 'releases/') }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          concurrent_skipping: 'same_content_newer'
          skip_after_successful_duplicate: 'true'
          cancel_others: 'true'
          paths: '["Cargo.toml", "Cargo.lock", "easytier/**", ".github/workflows/core.yml", ".github/workflows/install_rust.sh"]'
  setup-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Setup OpenHarmony SDK (5.1.0 Native only)
        uses: openharmony-rs/setup-ohos-sdk@v0.2
        with:
          version: "5.1.0"
          components: "native"
        
      - name: Move Native SDK to /usr/local/ohos-sdk/linux/native
        run: |
          echo "Detected Native SDK path: ${{ steps.setup-sdk.outputs.ohos_sdk_native }}"
          sudo mkdir -p /usr/local/ohos-sdk/linux
          sudo cp -r "${{ steps.setup-sdk.outputs.ohos_sdk_native }}" /usr/local/ohos-sdk/linux/native
          echo "Native SDK moved to /usr/local/ohos-sdk/linux/native"

      - name: Verify SDK installation
        run: |
          ls -la /usr/local/ohos-sdk/linux/native
          echo "Native SDK path: /usr/local/ohos-sdk/linux/native"
